//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BitCoinsWebApp.DAL.Entites
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BitCoinsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BitCoinsEntities object using the connection string found in the 'BitCoinsEntities' section of the application configuration file.
        /// </summary>
        public BitCoinsEntities() : base("name=BitCoinsEntities", "BitCoinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BitCoinsEntities object.
        /// </summary>
        public BitCoinsEntities(string connectionString) : base(connectionString, "BitCoinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BitCoinsEntities object.
        /// </summary>
        public BitCoinsEntities(EntityConnection connection) : base(connection, "BitCoinsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserAccount> UserAccounts
        {
            get
            {
                if ((_UserAccounts == null))
                {
                    _UserAccounts = base.CreateObjectSet<UserAccount>("UserAccounts");
                }
                return _UserAccounts;
            }
        }
        private ObjectSet<UserAccount> _UserAccounts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserAccounts(UserAccount userAccount)
        {
            base.AddObject("UserAccounts", userAccount);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitCoinsModel", Name="UserAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserAccount object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="bitCoinsQR">Initial value of the BitCoinsQR property.</param>
        /// <param name="bitCoinsCode">Initial value of the BitCoinsCode property.</param>
        /// <param name="iDRole">Initial value of the IDRole property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static UserAccount CreateUserAccount(global::System.Int32 id, global::System.String userName, global::System.String password, global::System.String name, global::System.Int32 age, global::System.String gender, global::System.String bitCoinsQR, global::System.String bitCoinsCode, global::System.Int32 iDRole, global::System.String address, global::System.Boolean isActive)
        {
            UserAccount userAccount = new UserAccount();
            userAccount.ID = id;
            userAccount.UserName = userName;
            userAccount.Password = password;
            userAccount.Name = name;
            userAccount.Age = age;
            userAccount.Gender = gender;
            userAccount.BitCoinsQR = bitCoinsQR;
            userAccount.BitCoinsCode = bitCoinsCode;
            userAccount.IDRole = iDRole;
            userAccount.Address = address;
            userAccount.IsActive = isActive;
            return userAccount;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, "Age");
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BitCoinsQR
        {
            get
            {
                return _BitCoinsQR;
            }
            set
            {
                OnBitCoinsQRChanging(value);
                ReportPropertyChanging("BitCoinsQR");
                _BitCoinsQR = StructuralObject.SetValidValue(value, false, "BitCoinsQR");
                ReportPropertyChanged("BitCoinsQR");
                OnBitCoinsQRChanged();
            }
        }
        private global::System.String _BitCoinsQR;
        partial void OnBitCoinsQRChanging(global::System.String value);
        partial void OnBitCoinsQRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BitCoinsCode
        {
            get
            {
                return _BitCoinsCode;
            }
            set
            {
                OnBitCoinsCodeChanging(value);
                ReportPropertyChanging("BitCoinsCode");
                _BitCoinsCode = StructuralObject.SetValidValue(value, false, "BitCoinsCode");
                ReportPropertyChanged("BitCoinsCode");
                OnBitCoinsCodeChanged();
            }
        }
        private global::System.String _BitCoinsCode;
        partial void OnBitCoinsCodeChanging(global::System.String value);
        partial void OnBitCoinsCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDParent
        {
            get
            {
                return _IDParent;
            }
            set
            {
                OnIDParentChanging(value);
                ReportPropertyChanging("IDParent");
                _IDParent = StructuralObject.SetValidValue(value, "IDParent");
                ReportPropertyChanged("IDParent");
                OnIDParentChanged();
            }
        }
        private Nullable<global::System.Int32> _IDParent;
        partial void OnIDParentChanging(Nullable<global::System.Int32> value);
        partial void OnIDParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDRole
        {
            get
            {
                return _IDRole;
            }
            set
            {
                OnIDRoleChanging(value);
                ReportPropertyChanging("IDRole");
                _IDRole = StructuralObject.SetValidValue(value, "IDRole");
                ReportPropertyChanged("IDRole");
                OnIDRoleChanged();
            }
        }
        private global::System.Int32 _IDRole;
        partial void OnIDRoleChanging(global::System.Int32 value);
        partial void OnIDRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false, "Address");
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value, "IsActive");
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    }

    #endregion

}
